### ISSUE TITLE
Exchange 2016 Setup Error Copying mmc.exe.config

### ISSUE THREAD

**Issue by YuriySamorodov** [MicrosoftDocs/OfficeDocs-Exchange#681]
While setting up Exchange 2016 Management tools on Windows 10 Version 1803 Build 17134.590 it would throw an error:
```
Error:
The following error was generated when "$error.Clear(); 
          if (Test-Path ($Env:SystemRoot + "\system32\mmc.exe")) {Copy-Item -Path ($RoleInstallPath+"Bin\mmc.exe.config") -Destination (Split-Path (where.exe mmc)) -Force}
        " was run: "System.UnauthorizedAccessException: Access to the path 'C:\Windows\System32\mmc.exe.config' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String destinationPath, Boolean force, PowerShell ps)".

Error:
The following error was generated when "$error.Clear(); 
          if (Test-Path ($Env:SystemRoot + "\system32\mmc.exe")) {Copy-Item -Path ($RoleInstallPath+"Bin\mmc.exe.config") -Destination (Split-Path (where.exe mmc)) -Force}
        " was run: "System.UnauthorizedAccessException: Access to the path 'C:\Windows\System32\mmc.exe.config' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyFileInfoItem(FileInfo file, String destinationPath, Boolean force, PowerShell ps)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItemLocalOrToSession(String path, String destinationPath, Boolean recurse, Boolean Force, PowerShell ps)
   at Microsoft.PowerShell.Commands.FileSystemProvider.CopyItem(String path, String destinationPath, Boolean recurse)
   at System.Management.Automation.SessionStateInternal.CopyItem(CmdletProvider providerInstance, String path, String copyPath, Boolean recurse, CmdletProviderContext context)".
```
Running setup.exe as an Administrator will make no difference.

**Comment by scanum** [comment]
@YuriySamorodov  - thank you for submitting feedback.

I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.

Please follow this link to contact support for business products:  https://docs.microsoft.com/office365/admin/contact-support-for-business-products

Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close
